### ISSUE TITLE
ティザーサイトのレビュー

### ISSUE THREAD

**Issue by ririko25** [php-jp/phpcon2020-kansai#31]
サイトURL：https://2020.kphpug.jp/

XDデザインカンプ：https://xd.adobe.com/view/b4a25519-dee2-4d34-6347-ccfe48be0ab7-c293/screen/db833d6c-b873-4e33-baae-3230f6e4508f/-2020-PC

修正箇所がありましたら、このissueに紐付けてissue立てをお願いします！

**Comment by sshono1210** [comment]
![Screen Shot 2020-02-17 at 11 04 12](https://user-images.githubusercontent.com/16553978/74618617-ee582900-5175-11ea-9012-c894bf11c77f.png)

「ホールカンファレンス」を「ホール＆カンファレンス」に修正

**Comment by sshono1210** [comment]
![Screen Shot 2020-02-17 at 11 09 57](https://user-images.githubusercontent.com/16553978/74618681-219ab800-5176-11ea-8780-2cee05c7cc2b.png)

「9回目」に修正お願いします

**Comment by SagaNaoko** [comment]
![image](https://user-images.githubusercontent.com/32927672/74619175-f618cd00-5177-11ea-971f-dc85df3f1cfa.png)
「関西PHPerの夏はこれがなくちゃ始まらない！」とありますが、季節的にちょっと違和感があります。

**Comment by Y-Kanoh** [comment]
問い合わせはメールで一元化することになっていたかと。
![68A97773-F994-4E82-B5C1-5D7D42A2C26E](https://user-images.githubusercontent.com/12679843/74622633-e81d7900-5184-11ea-8a2d-c25ae5a12081.jpeg)

**Comment by Y-Kanoh** [comment]
細かいですが、ボタンがちょっとボタンがズレているのが気になります！
(キャプチャはiPhone7です)
![8DFC79BB-5FB1-41B3-9D0E-8239E8A98BD8](https://user-images.githubusercontent.com/12679843/74622665-008d9380-5185-11ea-9e87-15246cb80f44.png)

**Comment by ririko25** [comment]
@sshono1210 @Y-Kanoh 

フィードバックいただきましてありがとうございます！
以下、修正対応内容を記載しております。

https://2020.kphpug.jp/

こちら&マークを入れるとエラーになってしまうので、一旦なしというお話になりました！
>「ホールカンファレンス」を「ホール＆カンファレンス」に修正お願いします

修正いたしました！
>「9回目」に修正お願いします

テーマに合わせた文言を考えていただけますと助かります！
>「関西PHPerの夏はこれがなくちゃ始まらない！」とありますが、季節的にちょっと違和感があります。

問い合わせ先のメールアドレスを教えていただけますでしょうか？
>問い合わせはメールで一元化することになっていたかと。

修正いたしました！
>細かいですが、ボタンがちょっと中央からズレているのが気になります！

**Comment by sshono1210** [comment]
@ririko25 

> テーマに合わせた文言を考えていただけますと助かります！

@Y-Kanoh さんに依頼中ですので、少々お待ちください 🙏 


> 問い合わせ先のメールアドレスを教えていただけますでしょうか？

phpcon.kansai@gmail.com でお願いします！

**Comment by Y-Kanoh** [comment]
こちらでいかがでしょうか。

**タイトル下**

`今年も` とありますが、去年は開催していないので、修正。

```
関西最大のPHPイベント開催決定！
```

**説明文**

初見ではどんなイベントかがわからないのでイベント内容を追記。

```
集え、PHPer！！
PHPerのGWはこの日が本番
あのPHPの祭典がついに帰ってきた！

当日はPHPに関するトークセッションのほか、懇親会やその他イベントを実施予定
「PHPカンファレンス関西」でPHPの未来をつくろう！
```

**Comment by ririko25** [comment]
@sshono1210 @Y-Kanoh 

文言作成いただきましてありがとうございます！

文言修正対応いたしましたので、ご確認お願いいたします！
https://2020.kphpug.jp/

**Comment by Y-Kanoh** [comment]
@ririko25 
対応ありがとうございます。

1点、「関西最大のPHPイベント開催決定！」は、説明文に含めるのではなく、タイトル下の「PHPカンファレンスが今年も開催」との差し替えでお願いできないでしょうか。

![AAD805A0-C507-4B99-8027-8C198A645E22](https://user-images.githubusercontent.com/12679843/74709098-ad3d4300-5261-11ea-8bb9-224a99386ad6.jpeg)

**Comment by ririko25** [comment]
@Y-Kanoh 

すいません、修正箇所の認識を間違えていました、修正いたしましたのでご確認のほどお願いします！
https://2020.kphpug.jp/

**Comment by ririko25** [comment]
@sshono1210 
お問い合わせ先を以下のメールアドレスに変更いたしました
phpcon.kansai@gmail.com でお願いします！

**Comment by Y-Kanoh** [comment]
@ririko25 
後出しですみません。
以下2点で問題が見つかっています。

## <meta>タグ内の文章が古いままになっている

<meta>タグ内の文章が「関西PHPerの夏は〜」のままになっています。
新しく差し込んだ「集え、PHPer！！〜」の文章に変更をお願いします。

## <title>タグ内の文章が「グランフロント」と記載されている

<title>タグ内の文章が「PHPカンファレンス関西2020 は 5月9日(土)にグランフロント大阪にて開催! 」になっています。開催はグランフロントではないので修正が必要です。

以下の文章に変更をお願いします。

```
PHPカンファレンス関西2020 は 5月9日(土)に開催!
```

**Comment by ririko25** [comment]
@Y-Kanoh 

こちら修正いたしました！

ご確認のほどよろしくお願いいたします。

>タグ内の文章が古いままになっている

><title>タグ内の文章が「グランフロント」と記載されている

**Comment by Y-Kanoh** [comment]
確認できました！
ありがとうございます！！
