### ISSUE TITLE
【本番サイト】スポンサーセクション

### ISSUE THREAD

**Issue by ririko25** [php-jp/phpcon2020-kansai#49]
### スポンサーセクション
- [x] スポンサー様企業ロゴ
- [x] ランクの表示
- [x] スポンサー企業紹介ページへのリンクボタン

### スポンサーセクション
- [x] ランクによるロゴ表示サイズの変更は必要
- [x] ロゴクリックでスポンサー企業のサイトに別タブでジャンプ

**Comment by ririko25** [comment]
質問事項
- スポンサーランクの種類を教えてください（ゴールドとかシルバーとか）
- 表示する内容の認識が上記の内容で問題ないかご確認いただきたいです。
- 同じランクのスポンサー様表示順は、申し込みが早かった順で問題ないでしょうか？

**Comment by Y-Kanoh** [comment]
> スポンサーランクの種類を教えてください（ゴールドとかシルバーとか）

スポンサーランクは以下の通りです。

* プラチナ（限定2団体）
* ゴールド（最大8団体）
* シルバー（制限数なし）
* フード&ドリンク（限定1団体）

価格は プラチナ > ゴールド > シルバー の順です。
また、フード&ドリンク スポンサーは、ゴールド スポンサー と同じ金額です。
そのため、ロゴのサイズはゴールドとフード&ドリンクで同じがいいかと思います。

-------

> 表示する内容の認識が上記の内容で問題ないかご確認いただきたいです。

はい、問題ありません。

------

> 同じランクのスポンサー様表示順は、申し込みが早かった順で問題ないでしょうか？

はい、申し込み順で大丈夫です。

**Comment by ririko25** [comment]
@Y-Kanoh @sshono1210

スポンサーセクションのデザイン作成が完了いたしました！

以下のURLからご確認いただけます。

PC: https://xd.adobe.com/view/b4a25519-dee2-4d34-6347-ccfe48be0ab7-c293/screen/b6104130-6203-403c-baec-d2719e969e78/-2020-PC-9/
SP: https://xd.adobe.com/view/b4a25519-dee2-4d34-6347-ccfe48be0ab7-c293/screen/a722d096-5094-47b5-a684-d99b26f467cb/-2020-SP

以下ページ仕様です。
- スポンサーが増えて二段目ができた場合は中央寄せではなく左寄せで表示させる
- 企業ロゴを押すと企業のページにリンクする

こちらのデザインで問題なければ、コーディングの方進めさせていただきます。

ご確認のほどよろしくお願いいたします！

**Comment by Y-Kanoh** [comment]
> スポンサーが増えて二段目ができた場合は中央寄せではなく左寄せで表示させる

上記画像のように、二段目がロゴ1つだけのような時は、歯抜けっぽく見えるため、中央の方がいいかなと思いました。

細かいですが、企業ロゴクリックでのページジャンプは、別タブで開くようにお願いします。

また、メディアスポンサーについて、ロゴの掲載を確認中ですので、掲載する場合は food & drink スポンサーと同じ様に追加していただければと思います。（決まり次第お伝えしますね）

以上、よろしくお願いします！
