### ISSUE TITLE
【本番サイト】過去のサイトへのリンク

### ISSUE THREAD

**Issue by ririko25** [php-jp/phpcon2020-kansai#51]
過去サイトへのリンクセクションを追加してください。

aboutセクションに追加

2018年度も追加お願いします。

参考サイト：https://2018.kphpug.jp/

参考セクションスクショ：
![スクリーンショット 2020-03-17 13 46 53](https://user-images.githubusercontent.com/29808916/76822907-d13a7700-6855-11ea-8e39-9e20b37b367d.png)

**Comment by ririko25** [comment]
@Y-Kanoh @sshono1210

過去サイトへのリンクを作成いたしました。

以下のURLからご確認いただけます。

PC: https://xd.adobe.com/view/b4a25519-dee2-4d34-6347-ccfe48be0ab7-c293/screen/b6104130-6203-403c-baec-d2719e969e78/-2020-PC-9/
SP: https://xd.adobe.com/view/b4a25519-dee2-4d34-6347-ccfe48be0ab7-c293/screen/a722d096-5094-47b5-a684-d99b26f467cb/-2020-SP

- 2018年のリンクも追加しております。

こちらのデザインで問題なければ、コーディングの方進めさせていただきます。

ご確認のほどよろしくお願いいたします！

**Comment by Y-Kanoh** [comment]
OKです！
よろしくお願いします！！
