### ISSUE TITLE
【本番サイト】ハッシュタグの追加

### ISSUE THREAD

**Issue by ririko25** [php-jp/phpcon2020-kansai#52]
>"細かいことですが、ハッシュタグの記載もお願いします。ハッシュタグは以下の通り。
 #phpkansai "

ハッシュタグを以下のサイトのように記載のほどお願いします！
https://2017.kphpug.jp/

**Comment by ririko25** [comment]
@Y-Kanoh @sshono1210

ハッシュタグの追加が完了いたしましたのでご連絡いたします。

以下のURLからご確認いただけます。

PC: https://xd.adobe.com/view/b4a25519-dee2-4d34-6347-ccfe48be0ab7-c293/screen/b6104130-6203-403c-baec-d2719e969e78/-2020-PC-9/
SP: https://xd.adobe.com/view/b4a25519-dee2-4d34-6347-ccfe48be0ab7-c293/screen/a722d096-5094-47b5-a684-d99b26f467cb/-2020-SP

- ハッシュタグの記載というご依頼でしたが、
それとは別に、PC時に固定で表示されているシェア部分がスマホになった際に表示されなくなる問題が発生しておりましたので、一番下のセクションにハッシュタグとシェアを表示するセクションを一つ切らせていただきました。

こちらのデザインで問題なければ、コーディングの方進めさせていただきます。

ご確認のほどよろしくお願いいたします！

**Comment by Y-Kanoh** [comment]
OKです。
（"みんなのツイートを覗いてみよう" という文言、いいですね。）

よろしくお願いします。
