### ISSUE TITLE
【コーディング 】スポンサーページ

### ISSUE THREAD

**Issue by NaNagaiShiho** [php-jp/phpcon2020-kansai#53]
### カンプURL
pc
https://xd.adobe.com/view/b4a25519-dee2-4d34-6347-ccfe48be0ab7-c293/screen/b6104130-6203-403c-baec-d2719e969e78/-2020-PC-9
SP
https://xd.adobe.com/view/b4a25519-dee2-4d34-6347-ccfe48be0ab7-c293/screen/a722d096-5094-47b5-a684-d99b26f467cb/-2020-SP

スポンサーページセクション

### 記述場所
以下のファイル作成してください
/ components / top / Sponsor

**Comment by ririko25** [comment]
二段目ができたときは中央に持ってくる感じで調整
