### ISSUE TITLE
【コーディング 】過去のサイトへのリンク

### ISSUE THREAD

**Issue by NaNagaiShiho** [php-jp/phpcon2020-kansai#54]
### カンプURL
PC:
https://xd.adobe.com/view/b4a25519-dee2-4d34-6347-ccfe48be0ab7-c293/screen/b6104130-6203-403c-baec-d2719e969e78/-2020-PC-9
SP:
https://xd.adobe.com/view/b4a25519-dee2-4d34-6347-ccfe48be0ab7-c293/screen/a722d096-5094-47b5-a684-d99b26f467cb/-2020-SP-12

aboutページセクション
現在存在しているアバウトページに追加でコーディングしてください。

### 記述場所
/ components / top / About

### リンク先URL
https://2018.kphpug.jp/

**Comment by ririko25** [comment]
こちらレビューOK、マージはまだしないでくだいさい！
